language : cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      compiler: gcc
    - os: linux  
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      
before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.tar.gz"
      mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/deps/cmake
      export PATH="${TRAVIS_BUILD_DIR}/deps/cmake/bin:${PATH}";
      virtualenv ~/wstest
      source ~/wstest/bin/activate
      pip install autobahntestsuite
    else
      brew update && brew upgrade cmake || brew install cmake;
      brew install zlib
    fi
    
script:
  - mkdir build
  - cd build
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl .. && make;
    else
      cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" .. && make;
      ctest -V;
      cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" .. && make;
      ctest -V;
    fi
     
notifications:
  email: false
  
